### PR TITLE
try yarn for travis as part of a central team spike

### PR DESCRIPTION
**Pull request by sulthan-ahmed**

### CODE REVIEW

**Comment by easternbloc** [comment]
@sulthan-ahmed could you add a description to this PR please. What are the benefits of yarn etc etc.

**Comment by easternbloc** [comment]
@sulthan-ahmed

**Comment by sulthan-ahmed** [comment]
Sorry @easternbloc dude.  At this moment, I'm not suggesting merging the PR after doing a bit more investigation.  See the (Key findings for Yarn)[https://github.com/UKHomeOffice/central-devteam-board/issues/63#issuecomment-259445083]

**Comment by easternbloc** [comment]
Please ensure you link any findings to the PR in the future this could have been merged 🆘

**Comment by sulthan-ahmed** [comment]
good point @easternbloc it was always experimental with travis.  Perhaps, I should have also have said please do not merge in heading too

**Pull request closed without merging**
