### PR TITLE
Add a link and complementing copy for survey links to confirmation pa…

### PR DESCRIPTION
**Pull request by JoeChapman**
…ge of each journey

### CODE REVIEW

**Comment by lennym** [comment]
I don't think translations is the right place for the survey urls. I'd move them to config.

**Comment by lennym** [comment]
This would be better implemented as a behaviour than a controller. By creating a controller that extends from the core controller module then locals that are set in the [application-wide base controller](https://github.com/UKHomeOffice/firearms/blob/master/apps/common/controllers/base.js) are not included since that controler is no longer in the inheritance/prototype chain.

By implementing as a behaviour then the parent controller and the inheritance chain is not affected, as it is composed onto whatever underlying controllers are in place.

**Comment by JoeChapman** [comment]
Ok, never written a behaviour before, I'll give it a shot though. The words you used appear to conspire into a type of logic so I'll update on Monday

**Comment by lennym** [comment]
There's some docs for behaviours at https://ukhomeofficeforms.github.io/hof-guide/documentation/#behaviours which should (hopefully!) be helpful. Would appreciate feedback/improvements on the docs if there's anything that you think would help.

**Pull request merged**
