### PR TITLE
Ensure we rebuild the container and it's packages when we build it.

### PR DESCRIPTION
**Pull request by easternbloc**

### CODE REVIEW

**Comment by lennym** [comment]
What's the logic behind doing all of those things twice?

**Comment by lennym** [comment]
Would it not be easier just to build it with `--no-cache`?

**Comment by easternbloc** [comment]
wait a mo

**Comment by easternbloc** [comment]
Ignore my previous comments I don't think we'll rebuild this enough to warrant the extra confusion.

**Comment by easternbloc** [comment]
@lennym @joefitter ping!

**Pull request merged**
